# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b8d00d1bf76110218d3976b5f20c26d"
application_url = "https://progressive-seattle-already-finite.trycloudflare.com"
embedded = true
name = "Testing"
handle = "testing-1593"

[build]
include_config_on_deploy = true
dev_store_url = "annan-test.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shipping, write_shipping, read_orders,write_orders,read_locales,read_discounts,write_products,read_customers, read_inventory, write_inventory, read_locations, read_markets, read_products"

[auth]
redirect_urls = [
  "https://progressive-seattle-already-finite.trycloudflare.com/auth/callback",
  "https://progressive-seattle-already-finite.trycloudflare.com/auth/shopify/callback",
  "https://progressive-seattle-already-finite.trycloudflare.com/api/auth/callback",
]

[pos]
embedded = false
